const LocalDataKeys = {
	//保存到本地数据的key定义集
	
	CHANNAL_CHANNELINFO_KEY:'CHANNAL_CHANNELINFO_KEY',//渠道信息
	HTTP_CURR_HOST_KEY:'CHANNAL_CURR_HOST_KEY',//渠道信息
	LAUNCHIMAGE_FILENAME_KEY:'LAUNCHIMAGE_FILENAME_KEY',//启动图缓存KEY
	
	LOGIN_LOGININFO_KEY:"LOGIN_LOGININFO_KEY",//登录&注册成功后返回的公用登录信息
	CHARACTER_PLYAERINFO_KEY:"CHARACTER_PLYAERINFO_KEY",//当前登录用户信息
	SAFETY_QUESTINFO_KEY:"SAFETY_QUESTINFO_KEY",//密保问题列表
	//....
}

export default LocalDataKeys